import { Button, Center, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Auth from '../components/Auth/Auth'
import { getSession, useSession } from 'next-auth/react'
import { NextPage, NextPageContext } from 'next'

const Home: NextPage = () => {
	const {data} = useSession()
	console.log(data);
	return (
		<div>
			<Head>
				<title>Update Coffee Price</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center height='100vh'>
				<Auth session={data}/>
			</Center>
		</div>
	)
}


export async function getServerSideProps(context: NextPageContext) {
	const session = await getSession(context)
	return {
		props: {
			session,
		},
	}
}

export default Home
