import { Center } from '@chakra-ui/react'
import { NextPage, NextPageContext } from 'next'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Auth from '../components/Auth/Auth'
import { prisma } from '../lib/prismadb'

interface CoffeeData {
	coffee: {
		id: string
		name: string
		imageUrl: string
		price: string
		qid: string
	}
}

const Home = ({ coffee }: CoffeeData) => {
	const { data: session } = useSession()
	console.log('session is: ', session)
	return (
		<div>
			<Head>
				<title>Update Coffee Price</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center height="100vh">
				{session ? (
					session.user.admin === true ? (
						'Here Data Input'
					) : (
						'You Accsess Denied'
					)
				) : (
					<Auth session={session} />
				)}
			</Center>
		</div>
	)
}

export async function getServerSideProps(context: NextPageContext) {
	const session = await getSession(context)
	const coffee = prisma.coffee.findMany({
		select: {
			id: true,
			name: true,
			imageUrl: true,
			price: true,
			qid: true,
		},
	})
	return {
		props: {
			session,
			coffee: JSON.parse(JSON.stringify(coffee)),
		},
	}
}

export default Home
