import { Box, Center } from '@chakra-ui/react'
import { NextPageContext } from 'next'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import { useEffect } from 'react'
import Auth from '../components/Auth/Auth'
import ListOfCoffee, { Coffee } from '../components/ListOfCoffee/ListOfCoffee'
import { prisma } from '../lib/prismadb'

const Home = ({ coffee }: Coffee) => {
	const { data: session } = useSession()
	useEffect(() => {
		const setDBCoffee = async () => {
			await fetch('http://localhost:3000/api/create/coffee', {
				method: 'GET',
			})
		}
		setDBCoffee()
	}, [])
	return (
		<div>
			<Head>
				<title>Update Coffee Price</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center height="100vh">
				{session ? (
					session.user.admin === true ? (
						<Box>
							<ListOfCoffee coffee={coffee} />
						</Box>
					) : (
						'You Accsess Denied'
					)
				) : (
					<Auth session={session} />
				)}
			</Center>
		</div>
	)
}

export async function getServerSideProps(context: NextPageContext) {
	const session = await getSession(context)
	const coffee = await prisma.coffee.findMany({
		select: {
			id: true,
			img: true,
			name: true,
			price: true,
			description: true,
			qid: true,
		},
	})
	return {
		props: {
			session,
			coffee,
		},
	}
}

export default Home
